import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { FileDown } from 'lucide-react';

interface HealthExportProps {
  data: any;
  shopName?: string;
  shopType?: string;
  shopCity?: string;
}

export default function HealthExport({ data, shopName, shopType, shopCity }: HealthExportProps) {
  const exportPDF = () => {
    const doc = new jsPDF();
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });

    // --- Header ---
    doc.setFontSize(22);
    doc.setTextColor(0, 128, 128); // Teal
    doc.text('VyapaarVaani', 14, 20);
    doc.setFontSize(14);
    doc.setTextColor(51, 51, 51);
    doc.text('Financial Health Profile', 14, 28);

    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    const vendorLine = [
      shopName && `Vendor: ${shopName}`,
      shopType && `Business: ${shopType}`,
      shopCity && `City: ${shopCity}`,
    ].filter(Boolean).join(' | ');
    if (vendorLine) doc.text(vendorLine, 14, 36);
    doc.text(`Generated: ${dateStr}`, 14, 42);

    // Divider
    doc.setDrawColor(0, 128, 128);
    doc.setLineWidth(0.5);
    doc.line(14, 46, 196, 46);

    // --- Score Summary ---
    doc.setFontSize(14);
    doc.setTextColor(51, 51, 51);
    doc.text(`Financial Health Score: ${data.score}/100 — ${data.tier}`, 14, 56);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Days of data recorded: ${data.days_recorded}`, 14, 64);
    doc.text(`Average daily earnings: Rs. ${data.avg_daily_earnings?.toLocaleString('en-IN') || '0'}`, 14, 70);
    if (data.unique_items) {
      doc.text(`Unique items tracked: ${data.unique_items}`, 14, 76);
    }

    // --- Criteria Table ---
    const tableData = (data.criteria || []).map((c: any) => [
      c.name,
      `${c.points_earned}`,
      `${c.points_max}`,
      c.status
    ]);

    autoTable(doc, {
      startY: 84,
      head: [['Criterion', 'Score', 'Max', 'Status']],
      body: tableData,
      theme: 'grid',
      headStyles: {
        fillColor: [0, 128, 128],
        textColor: [255, 255, 240],
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: { fontSize: 9 },
      columnStyles: {
        1: { halign: 'center' },
        2: { halign: 'center' },
      },
    });

    let finalY = (doc as any).lastAutoTable.finalY || 84;

    // --- Credit Profile Estimate ---
    if (data.loan_estimate && data.score >= 45) {
      finalY += 12;
      doc.setFontSize(11);
      doc.setTextColor(0, 128, 128);
      doc.text('Credit Profile Estimate', 14, finalY);

      finalY += 8;
      doc.setFontSize(9);
      doc.setTextColor(51, 51, 51);
      const creditText = `Based on your recorded earnings, your estimated credit profile is up to Rs. ${data.loan_estimate.toLocaleString('en-IN')}. This is based on the standard microfinance formula of 3x monthly average income.`;
      const splitCredit = doc.splitTextToSize(creditText, 175);
      doc.text(splitCredit, 14, finalY);
      finalY += splitCredit.length * 5;
    }

    // --- Resources ---
    finalY += 12;
    doc.setFontSize(10);
    doc.setTextColor(0, 128, 128);
    doc.text('Resources', 14, finalY);
    finalY += 7;
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text('PM SVANidhi Scheme: pmsvnidhi.mohua.gov.in', 14, finalY);
    finalY += 5;
    doc.text('National Urban Livelihoods Mission: nulm.gov.in', 14, finalY);

    // --- Footer ---
    finalY += 12;
    doc.setDrawColor(0, 128, 128);
    doc.setLineWidth(0.3);
    doc.line(14, finalY, 196, finalY);
    finalY += 6;

    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    const disclaimer = data.disclaimer || '';
    const splitDisclaimer = doc.splitTextToSize(disclaimer, 175);
    doc.text(splitDisclaimer, 14, finalY);
    finalY += splitDisclaimer.length * 4;

    doc.text(
      'This document was generated by VyapaarVaani from voice-recorded business data. It is not a formal financial document.',
      14, finalY + 2
    );

    // --- Save ---
    const safeName = (shopName || 'Vendor').replace(/[^a-zA-Z0-9]/g, '_');
    const monthStr = now.toISOString().slice(0, 7); // YYYY-MM
    doc.save(`VyapaarVaani_HealthProfile_${safeName}_${monthStr}.pdf`);
  };

  return (
    <button
      onClick={exportPDF}
      className='text-xs text-[#008080] font-bold underline underline-offset-2 flex items-center gap-1 hover:opacity-70'
    >
      Download your financial profile <FileDown size={10} />
    </button>
  );
}
